### ISSUE TITLE
初始化运行失败

### ISSUE THREAD

**Issue by CracKerMe** [BengBu-YueZhang/custom-vue-ssr#2]
export PORT=7070 NODE_ENV=development && node server.js

'export' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

------

运行环境: `windows10 `
node version: `8.15.0`
npm version: `6.4.1`

使用 npm 安装,安装好后 执行命令 `npm run dev` 出现上面错误

**Comment by CracKerMe** [comment]
我在Mac 上运行成功 `npm run dev`后， 先后执行 `npm run build:prod` `npm start`, 结果 访问页面的时候依旧报错 `document is not defined`, 请问您本地 线上预览 的时候没发现这个问题么？

**Comment by BengBu-YueZhang** [comment]
> 我在Mac 上运行成功 `npm run dev`后， 先后执行 `npm run build:prod` `npm start`, 结果 访问页面的时候依旧报错 `document is not defined`, 请问您本地 线上预览 的时候没发现这个问题么？

好的，我看看。哈哈，最近工作太忙了。

**Comment by BengBu-YueZhang** [comment]
https://github.com/vuejs/vue-router/issues/2380

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/48#issuecomment-375288454

https://github.com/webpack-contrib/mini-css-extract-plugin/issues/90

https://github.com/vuejs/vue-ssr-docs/issues/196

**Comment by BengBu-YueZhang** [comment]
我会尝试更新一个版本。

**Comment by CracKerMe** [comment]
> 我会尝试更新一个版本。

OK，我自己也手写的一个脚手架，，，但是需要提取css的时候就出了问题 

我用的插件：
`"mini-css-extract-plugin": "^0.8.0"`
**webpack.base.config.js**
`const MiniCssExtractPlugin = require('mini-css-extract-plugin')`

......

{
        test: /\.scss$/,
        use: ['vue-style-loader', 'css-loader', 'sass-loader']
},
{
        test: /\.css$/,
        use: [
          process.env.NODE_ENV !== 'production'
            ? 'vue-style-loader'
            : MiniCssExtractPlugin.loader,
          'css-loader'
        ]
}

......

plugins: [
    new VueLoaderPlugin(),
    new MiniCssExtractPlugin({
      filename: '[name].min.css',
      allChunks: false
    })
  ]
`
当前 会把所有组件包括加载的子组件的 scss 全部渲染到页面的一个标签里面，很显然不利于优化，，，，但是没有其他的办法 哎

**Comment by BengBu-YueZhang** [comment]
> > 我会尝试更新一个版本。
> 
> OK，我自己也手写的一个脚手架，，，但是需要提取css的时候就出了问题
> 
> 我用的插件：
> `"mini-css-extract-plugin": "^0.8.0"`
> **webpack.base.config.js**
> `const MiniCssExtractPlugin = require('mini-css-extract-plugin')`
> 
> ......
> 
> {
> test: /.scss$/,
> use: ['vue-style-loader', 'css-loader', 'sass-loader']
> },
> {
> test: /.css$/,
> use: [
> process.env.NODE_ENV !== 'production'
> ? 'vue-style-loader'
> : MiniCssExtractPlugin.loader,
> 'css-loader'
> ]
> }
> 
> ......
> 
> plugins: [
> new VueLoaderPlugin(),
> new MiniCssExtractPlugin({
> filename: '[name].min.css',
> allChunks: false
> })
> ]
> `
> 当前 会把所有组件包括加载的子组件的 scss 全部渲染到页面的一个标签里面，很显然不利于优化，，，，但是没有其他的办法 哎

你在拉一下代码，尝试一下，我提交了更新

**Comment by CracKerMe** [comment]
公司的windows 设备目前 还没法 `npm start`

**Comment by CracKerMe** [comment]
老哥 你的代码 我还是没跑起来,但是 我借鉴你的这段代码的写法,成功的实现了功能 并且 不在报错`document is not defined`

`
class ServerMiniCssExtractPlugin extends MiniCssExtractPlugin {
  getCssChunkObject(mainChunk) {
    return {};
  }
}
`
感谢老哥,,,现在就差 uglifyjs 与minify 了

**Comment by CracKerMe** [comment]
有兴趣的话 我也分享我的脚手架 您看看 有啥地方可以修改的

**Comment by BengBu-YueZhang** [comment]
> 有兴趣的话 我也分享我的脚手架 您看看 有啥地方可以修改的

可能和windows的电脑有关，命令我改下

**Comment by CracKerMe** [comment]
> > 有兴趣的话 我也分享我的脚手架 您看看 有啥地方可以修改的
> 
> 可能和windows的电脑有关，命令我改下

cross-env 就好

**Comment by CracKerMe** [comment]
https://github.com/CracKerMe/vue-ssr-cli  哥们 你看下我写的

**Comment by BengBu-YueZhang** [comment]
> https://github.com/CracKerMe/vue-ssr-cli 哥们 你看下我写的

老铁，koa版本可以跑了
